name: Build and Release Windows Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Windows binary (optimized)
        run: go build -ldflags="-H=windowsgui -s -w" -o folder-ripper.exe main.go

      - name: Download UPX
        run: |
          curl -LO https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip
          unzip upx-4.2.1-win64.zip

      - name: Compress binary with UPX
        run: ./upx-4.2.1-win64/upx --best --lzma folder-ripper.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: folder-ripper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
